// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHAmK0qW7PZe3_lasZUDTD9gb2q9VD_Yo',
    appId: '1:572056730908:web:25018b86fafc99c93f4ed9',
    messagingSenderId: '572056730908',
    projectId: 'shoppinglist-9540c',
    authDomain: 'shoppinglist-9540c.firebaseapp.com',
    storageBucket: 'shoppinglist-9540c.firebasestorage.app',
    measurementId: 'G-8XJBL63W09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3I2QR2rCeFJsomkfJrT4T9UsOPeF7BBI',
    appId: '1:572056730908:android:1f8c4977fbe49a923f4ed9',
    messagingSenderId: '572056730908',
    projectId: 'shoppinglist-9540c',
    storageBucket: 'shoppinglist-9540c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHQGeGOn7GyS1KQssmgj47Kh2lhTqAPO8',
    appId: '1:572056730908:ios:0d4d192024ad7e373f4ed9',
    messagingSenderId: '572056730908',
    projectId: 'shoppinglist-9540c',
    storageBucket: 'shoppinglist-9540c.firebasestorage.app',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHQGeGOn7GyS1KQssmgj47Kh2lhTqAPO8',
    appId: '1:572056730908:ios:0d4d192024ad7e373f4ed9',
    messagingSenderId: '572056730908',
    projectId: 'shoppinglist-9540c',
    storageBucket: 'shoppinglist-9540c.firebasestorage.app',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHAmK0qW7PZe3_lasZUDTD9gb2q9VD_Yo',
    appId: '1:572056730908:web:e66f6df654bb56af3f4ed9',
    messagingSenderId: '572056730908',
    projectId: 'shoppinglist-9540c',
    authDomain: 'shoppinglist-9540c.firebaseapp.com',
    storageBucket: 'shoppinglist-9540c.firebasestorage.app',
    measurementId: 'G-DZXLC6QQH2',
  );
}
